# CMake generated Testfile for 
# Source directory: /home/intel/Documents/CVSDK_FDFR/face-access-control/cvservice/paho-src/test
# Build directory: /home/intel/Documents/CVSDK_FDFR/face-access-control/cvservice/pahomqtt-prefix/src/pahomqtt-build/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test1-1-single-thread-client "/home/intel/Documents/CVSDK_FDFR/face-access-control/cvservice/pahomqtt-prefix/src/pahomqtt-build/test/test1" "--test_no" "1" "--connection" "tcp://localhost:1883")
set_tests_properties(test1-1-single-thread-client PROPERTIES  TIMEOUT "540")
add_test(test1-2-multithread-callbacks "/home/intel/Documents/CVSDK_FDFR/face-access-control/cvservice/pahomqtt-prefix/src/pahomqtt-build/test/test1" "--test_no" "2" "--connection" "tcp://localhost:1883")
set_tests_properties(test1-2-multithread-callbacks PROPERTIES  TIMEOUT "540")
add_test(test1-3-connack-return-codes "/home/intel/Documents/CVSDK_FDFR/face-access-control/cvservice/pahomqtt-prefix/src/pahomqtt-build/test/test1" "--test_no" "3" "--connection" "tcp://localhost:1883")
set_tests_properties(test1-3-connack-return-codes PROPERTIES  TIMEOUT "540")
add_test(test1-4-client-persistence "/home/intel/Documents/CVSDK_FDFR/face-access-control/cvservice/pahomqtt-prefix/src/pahomqtt-build/test/test1" "--test_no" "4" "--connection" "tcp://localhost:1883")
set_tests_properties(test1-4-client-persistence PROPERTIES  TIMEOUT "540")
add_test(test1-5-disconnect-with-quiesce "/home/intel/Documents/CVSDK_FDFR/face-access-control/cvservice/pahomqtt-prefix/src/pahomqtt-build/test/test1" "--test_no" "5" "--connection" "tcp://localhost:1883")
set_tests_properties(test1-5-disconnect-with-quiesce PROPERTIES  TIMEOUT "540")
add_test(test1-6-connlost-will-message "/home/intel/Documents/CVSDK_FDFR/face-access-control/cvservice/pahomqtt-prefix/src/pahomqtt-build/test/test1" "--test_no" "6" "--connection" "tcp://localhost:1883" "--proxy_connection" "tcp://localhost:1884")
set_tests_properties(test1-6-connlost-will-message PROPERTIES  TIMEOUT "540")
add_test(test1-7-connlost-binary-will-message "/home/intel/Documents/CVSDK_FDFR/face-access-control/cvservice/pahomqtt-prefix/src/pahomqtt-build/test/test1" "--test_no" "7" "--connection" "tcp://localhost:1883" "--proxy_connection" "tcp://localhost:1884")
set_tests_properties(test1-7-connlost-binary-will-message PROPERTIES  TIMEOUT "540")
add_test(test2-1-multiple-threads-single-client "/home/intel/Documents/CVSDK_FDFR/face-access-control/cvservice/pahomqtt-prefix/src/pahomqtt-build/test/test2" "--connection" "tcp://localhost:1883")
set_tests_properties(test2-1-multiple-threads-single-client PROPERTIES  TIMEOUT "540")
add_test(test3-1-ssl-conn-to-non-SSL-broker "/home/intel/Documents/CVSDK_FDFR/face-access-control/cvservice/pahomqtt-prefix/src/pahomqtt-build/test/test3" "--test_no" "1" "--hostname" "localhost" "--client_key" "/test/ssl/client.pem" "--server_key" "/test/ssl/test-root-ca.crt")
set_tests_properties(test3-1-ssl-conn-to-non-SSL-broker PROPERTIES  TIMEOUT "540")
add_test(test3-2as-mutual-ssl-auth-single-thread "/home/intel/Documents/CVSDK_FDFR/face-access-control/cvservice/pahomqtt-prefix/src/pahomqtt-build/test/test3" "--test_no" "2" "--hostname" "localhost" "--client_key" "/test/ssl/client.pem" "--server_key" "/test/ssl/test-root-ca.crt")
set_tests_properties(test3-2as-mutual-ssl-auth-single-thread PROPERTIES  TIMEOUT "540")
add_test(test3-2am-mutual-ssl-auth-multi-thread "/home/intel/Documents/CVSDK_FDFR/face-access-control/cvservice/pahomqtt-prefix/src/pahomqtt-build/test/test3" "--test_no" "3" "--hostname" "localhost" "--client_key" "/test/ssl/client.pem" "--server_key" "/test/ssl/test-root-ca.crt")
set_tests_properties(test3-2am-mutual-ssl-auth-multi-thread PROPERTIES  TIMEOUT "540")
add_test(test3-2b-mutual-ssl-broker-missing-client-cert "/home/intel/Documents/CVSDK_FDFR/face-access-control/cvservice/pahomqtt-prefix/src/pahomqtt-build/test/test3" "--test_no" "4" "--hostname" "localhost" "--client_key" "/test/ssl/client.pem" "--server_key" "/test/ssl/test-root-ca.crt")
set_tests_properties(test3-2b-mutual-ssl-broker-missing-client-cert PROPERTIES  TIMEOUT "540")
add_test(test3-2c-mutual-ssl-client-missing-broker-cert "/home/intel/Documents/CVSDK_FDFR/face-access-control/cvservice/pahomqtt-prefix/src/pahomqtt-build/test/test3" "--test_no" "5" "--hostname" "localhost" "--client_key" "/test/ssl/client.pem" "--server_key" "/test/ssl/test-root-ca.crt")
set_tests_properties(test3-2c-mutual-ssl-client-missing-broker-cert PROPERTIES  TIMEOUT "540")
add_test(test3-3as-broker-auth-server-cert-in-client-store-single-thread "/home/intel/Documents/CVSDK_FDFR/face-access-control/cvservice/pahomqtt-prefix/src/pahomqtt-build/test/test3" "--test_no" "6" "--hostname" "localhost" "--client_key" "/test/ssl/client.pem" "--server_key" "/test/ssl/test-root-ca.crt")
set_tests_properties(test3-3as-broker-auth-server-cert-in-client-store-single-thread PROPERTIES  TIMEOUT "540")
add_test(test3-3am-broker-auth-server-cert-in-client-store-multi-thread "/home/intel/Documents/CVSDK_FDFR/face-access-control/cvservice/pahomqtt-prefix/src/pahomqtt-build/test/test3" "--test_no" "7" "--hostname" "localhost" "--client_key" "/test/ssl/client.pem" "--server_key" "/test/ssl/test-root-ca.crt")
set_tests_properties(test3-3am-broker-auth-server-cert-in-client-store-multi-thread PROPERTIES  TIMEOUT "540")
add_test(test3-3b-broker-auth-client-missing-broker-cert "/home/intel/Documents/CVSDK_FDFR/face-access-control/cvservice/pahomqtt-prefix/src/pahomqtt-build/test/test3" "--test_no" "8" "--hostname" "localhost" "--client_key" "/test/ssl/client.pem" "--server_key" "/test/ssl/test-root-ca.crt")
set_tests_properties(test3-3b-broker-auth-client-missing-broker-cert PROPERTIES  TIMEOUT "540")
add_test(test3-4s-broker-auth-accept-invalid-certificate-single-thread "/home/intel/Documents/CVSDK_FDFR/face-access-control/cvservice/pahomqtt-prefix/src/pahomqtt-build/test/test3" "--test_no" "9" "--hostname" "localhost" "--client_key" "/test/ssl/client.pem" "--server_key" "/test/ssl/test-root-ca.crt")
set_tests_properties(test3-4s-broker-auth-accept-invalid-certificate-single-thread PROPERTIES  TIMEOUT "540")
add_test(test3-4m-broker-auth-accept-invalid-certificate-multi-thread "/home/intel/Documents/CVSDK_FDFR/face-access-control/cvservice/pahomqtt-prefix/src/pahomqtt-build/test/test3" "--test_no" "10" "--hostname" "localhost" "--client_key" "/test/ssl/client.pem" "--server_key" "/test/ssl/test-root-ca.crt")
set_tests_properties(test3-4m-broker-auth-accept-invalid-certificate-multi-thread PROPERTIES  TIMEOUT "540")
add_test(test4-1-basic-connect-subscribe-receive "/home/intel/Documents/CVSDK_FDFR/face-access-control/cvservice/pahomqtt-prefix/src/pahomqtt-build/test/test4" "--test_no" "1" "--connection" "tcp://localhost:1883")
set_tests_properties(test4-1-basic-connect-subscribe-receive PROPERTIES  TIMEOUT "540")
add_test(test4-2-connect-timeout "/home/intel/Documents/CVSDK_FDFR/face-access-control/cvservice/pahomqtt-prefix/src/pahomqtt-build/test/test4" "--test_no" "2" "--connection" "tcp://localhost:1883")
set_tests_properties(test4-2-connect-timeout PROPERTIES  TIMEOUT "540")
add_test(test4-3-multiple-client-objs-simultaneous-working "/home/intel/Documents/CVSDK_FDFR/face-access-control/cvservice/pahomqtt-prefix/src/pahomqtt-build/test/test4" "--test_no" "3" "--connection" "tcp://localhost:1883")
set_tests_properties(test4-3-multiple-client-objs-simultaneous-working PROPERTIES  TIMEOUT "540")
add_test(test4-4-send-receive-big-messages "/home/intel/Documents/CVSDK_FDFR/face-access-control/cvservice/pahomqtt-prefix/src/pahomqtt-build/test/test4" "--test_no" "4" "--connection" "tcp://localhost:1883")
set_tests_properties(test4-4-send-receive-big-messages PROPERTIES  TIMEOUT "540")
add_test(test4-5-connack-return-codes "/home/intel/Documents/CVSDK_FDFR/face-access-control/cvservice/pahomqtt-prefix/src/pahomqtt-build/test/test4" "--test_no" "5" "--connection" "tcp://localhost:1883")
set_tests_properties(test4-5-connack-return-codes PROPERTIES  TIMEOUT "540")
add_test(test4-6-ha-connections "/home/intel/Documents/CVSDK_FDFR/face-access-control/cvservice/pahomqtt-prefix/src/pahomqtt-build/test/test4" "--test_no" "6" "--connection" "tcp://localhost:1883")
set_tests_properties(test4-6-ha-connections PROPERTIES  TIMEOUT "540")
add_test(test4-7-pending-tokens "/home/intel/Documents/CVSDK_FDFR/face-access-control/cvservice/pahomqtt-prefix/src/pahomqtt-build/test/test4" "--test_no" "7" "--connection" "tcp://localhost:1883")
set_tests_properties(test4-7-pending-tokens PROPERTIES  TIMEOUT "540")
add_test(test4-8-incomplete-commands-requests "/home/intel/Documents/CVSDK_FDFR/face-access-control/cvservice/pahomqtt-prefix/src/pahomqtt-build/test/test4" "--test_no" "8" "--connection" "tcp://localhost:1883")
set_tests_properties(test4-8-incomplete-commands-requests PROPERTIES  TIMEOUT "540")
add_test(test5-1-ssl-connection-to-no-SSL-server "/home/intel/Documents/CVSDK_FDFR/face-access-control/cvservice/pahomqtt-prefix/src/pahomqtt-build/test/test5" "--test_no" "1" "--hostname" "localhost" "--client_key" "/test/ssl/client.pem" "--server_key" "/test/ssl/test-root-ca.crt")
set_tests_properties(test5-1-ssl-connection-to-no-SSL-server PROPERTIES  TIMEOUT "540")
add_test(test5-2a-multual-ssl-auth-certificates-in-place "/home/intel/Documents/CVSDK_FDFR/face-access-control/cvservice/pahomqtt-prefix/src/pahomqtt-build/test/test5" "--test_no" "2" "--hostname" "localhost" "--client_key" "/test/ssl/client.pem" "--server_key" "/test/ssl/test-root-ca.crt")
set_tests_properties(test5-2a-multual-ssl-auth-certificates-in-place PROPERTIES  TIMEOUT "540")
add_test(test5-2b-multual-ssl-auth-broker-missing-client-cert "/home/intel/Documents/CVSDK_FDFR/face-access-control/cvservice/pahomqtt-prefix/src/pahomqtt-build/test/test5" "--test_no" "3" "--hostname" "localhost" "--client_key" "/test/ssl/client.pem" "--server_key" "/test/ssl/test-root-ca.crt")
set_tests_properties(test5-2b-multual-ssl-auth-broker-missing-client-cert PROPERTIES  TIMEOUT "540")
add_test(test5-2c-multual-ssl-auth-client-missing-broker-cert "/home/intel/Documents/CVSDK_FDFR/face-access-control/cvservice/pahomqtt-prefix/src/pahomqtt-build/test/test5" "--test_no" "4" "--hostname" "localhost" "--client_key" "/test/ssl/client.pem" "--server_key" "/test/ssl/test-root-ca.crt")
set_tests_properties(test5-2c-multual-ssl-auth-client-missing-broker-cert PROPERTIES  TIMEOUT "540")
add_test(test5-2d-multual-ssl-auth-client-missing-client-cert "/home/intel/Documents/CVSDK_FDFR/face-access-control/cvservice/pahomqtt-prefix/src/pahomqtt-build/test/test5" "--test_no" "5" "--hostname" "localhost" "--client_key" "/test/ssl/client.pem" "--server_key" "/test/ssl/test-root-ca.crt")
set_tests_properties(test5-2d-multual-ssl-auth-client-missing-client-cert PROPERTIES  TIMEOUT "540")
add_test(test5-3a-server-auth-server-cert-in-client-store "/home/intel/Documents/CVSDK_FDFR/face-access-control/cvservice/pahomqtt-prefix/src/pahomqtt-build/test/test5" "--test_no" "6" "--hostname" "localhost" "--client_key" "/test/ssl/client.pem" "--server_key" "/test/ssl/test-root-ca.crt")
set_tests_properties(test5-3a-server-auth-server-cert-in-client-store PROPERTIES  TIMEOUT "540")
add_test(test5-3b-server-auth-client-missing-broker-cert "/home/intel/Documents/CVSDK_FDFR/face-access-control/cvservice/pahomqtt-prefix/src/pahomqtt-build/test/test5" "--test_no" "7" "--hostname" "localhost" "--client_key" "/test/ssl/client.pem" "--server_key" "/test/ssl/test-root-ca.crt")
set_tests_properties(test5-3b-server-auth-client-missing-broker-cert PROPERTIES  TIMEOUT "540")
add_test(test5-4-accept-invalid-certificates "/home/intel/Documents/CVSDK_FDFR/face-access-control/cvservice/pahomqtt-prefix/src/pahomqtt-build/test/test5" "--test_no" "8" "--hostname" "localhost" "--client_key" "/test/ssl/client.pem" "--server_key" "/test/ssl/test-root-ca.crt")
set_tests_properties(test5-4-accept-invalid-certificates PROPERTIES  TIMEOUT "540")
add_test(test6-restart-recovery "/home/intel/Documents/CVSDK_FDFR/face-access-control/cvservice/pahomqtt-prefix/src/pahomqtt-build/test/test6" "--connection" "tcp://localhost:1883")
set_tests_properties(test6-restart-recovery PROPERTIES  TIMEOUT "540")
add_test(test8-1-basic-connect-subscribe-receive "/home/intel/Documents/CVSDK_FDFR/face-access-control/cvservice/pahomqtt-prefix/src/pahomqtt-build/test/test8" "--test_no" "1" "--connection" "tcp://localhost:1883")
set_tests_properties(test8-1-basic-connect-subscribe-receive PROPERTIES  TIMEOUT "540")
add_test(test8-2-connect-timeout "/home/intel/Documents/CVSDK_FDFR/face-access-control/cvservice/pahomqtt-prefix/src/pahomqtt-build/test/test8" "--test_no" "2" "--connection" "tcp://localhost:1883")
set_tests_properties(test8-2-connect-timeout PROPERTIES  TIMEOUT "540")
add_test(test8-3-multiple-client-objects-simultaneous-working "/home/intel/Documents/CVSDK_FDFR/face-access-control/cvservice/pahomqtt-prefix/src/pahomqtt-build/test/test8" "--test_no" "3" "--connection" "tcp://localhost:1883")
set_tests_properties(test8-3-multiple-client-objects-simultaneous-working PROPERTIES  TIMEOUT "540")
add_test(test8-4-send-receive-big-messages "/home/intel/Documents/CVSDK_FDFR/face-access-control/cvservice/pahomqtt-prefix/src/pahomqtt-build/test/test8" "--test_no" "4" "--connection" "tcp://localhost:1883" "--size" "500000")
set_tests_properties(test8-4-send-receive-big-messages PROPERTIES  TIMEOUT "540")
add_test(test8-5a-all-ha-connections-out-of-service "/home/intel/Documents/CVSDK_FDFR/face-access-control/cvservice/pahomqtt-prefix/src/pahomqtt-build/test/test8" "--test_no" "5" "--connection" "tcp://localhost:1883")
set_tests_properties(test8-5a-all-ha-connections-out-of-service PROPERTIES  TIMEOUT "540")
add_test(test8-5b-all-ha-connections-out-of-service-except-the-last-one "/home/intel/Documents/CVSDK_FDFR/face-access-control/cvservice/pahomqtt-prefix/src/pahomqtt-build/test/test8" "--test_no" "6" "--connection" "tcp://localhost:1883")
set_tests_properties(test8-5b-all-ha-connections-out-of-service-except-the-last-one PROPERTIES  TIMEOUT "540")
add_test(test8-5c-all-ha-connections-out-of-service-except-the-first-one "/home/intel/Documents/CVSDK_FDFR/face-access-control/cvservice/pahomqtt-prefix/src/pahomqtt-build/test/test8" "--test_no" "7" "--connection" "tcp://localhost:1883")
set_tests_properties(test8-5c-all-ha-connections-out-of-service-except-the-first-one PROPERTIES  TIMEOUT "540")
add_test(test9-1-offline-buffering-send-disconnected "/home/intel/Documents/CVSDK_FDFR/face-access-control/cvservice/pahomqtt-prefix/src/pahomqtt-build/test/test9" "--test_no" "1" "--connection" "tcp://localhost:1883" "--proxy_connection" "tcp://localhost:1884")
set_tests_properties(test9-1-offline-buffering-send-disconnected PROPERTIES  TIMEOUT "540")
add_test(test9-2-offline-buffering-send-disconnected-serverURIs "/home/intel/Documents/CVSDK_FDFR/face-access-control/cvservice/pahomqtt-prefix/src/pahomqtt-build/test/test9" "--test_no" "2" "--connection" "tcp://localhost:1883" "--proxy_connection" "tcp://localhost:1884")
set_tests_properties(test9-2-offline-buffering-send-disconnected-serverURIs PROPERTIES  TIMEOUT "540")
add_test(test9-3-offline-buffering-auto-reconnect "/home/intel/Documents/CVSDK_FDFR/face-access-control/cvservice/pahomqtt-prefix/src/pahomqtt-build/test/test9" "--test_no" "3" "--connection" "tcp://localhost:1883" "--proxy_connection" "tcp://localhost:1884")
set_tests_properties(test9-3-offline-buffering-auto-reconnect PROPERTIES  TIMEOUT "540")
add_test(test9-4-offline-buffering-auto-reconnect-serverURIs "/home/intel/Documents/CVSDK_FDFR/face-access-control/cvservice/pahomqtt-prefix/src/pahomqtt-build/test/test9" "--test_no" "4" "--connection" "tcp://localhost:1883" "--proxy_connection" "tcp://localhost:1884")
set_tests_properties(test9-4-offline-buffering-auto-reconnect-serverURIs PROPERTIES  TIMEOUT "540")
add_test(test9-5-offline-buffering-max-buffered "/home/intel/Documents/CVSDK_FDFR/face-access-control/cvservice/pahomqtt-prefix/src/pahomqtt-build/test/test9" "--test_no" "5" "--connection" "tcp://localhost:1883" "--proxy_connection" "tcp://localhost:1884")
set_tests_properties(test9-5-offline-buffering-max-buffered PROPERTIES  TIMEOUT "540")
add_test(test9-6-offline-buffering-max-buffered-binary-will "/home/intel/Documents/CVSDK_FDFR/face-access-control/cvservice/pahomqtt-prefix/src/pahomqtt-build/test/test9" "--test_no" "6" "--connection" "tcp://localhost:1883" "--proxy_connection" "tcp://localhost:1884")
set_tests_properties(test9-6-offline-buffering-max-buffered-binary-will PROPERTIES  TIMEOUT "540")
